### ISSUE TITLE
File name problem under Windows

### ISSUE THREAD

**Issue by cavedude00** [csBlueChip/FlipperZero_WiiEC#1]
Windows considers the following files to have the same name:

gfx/img_6x8_D.c
gfx/img_6x8_d.c

If this project is worked with under Windows in any way, it will delete one of the two files. This will either cause the application to not compile, or if it does compile it won't run on the Flipper due to an unresolved symbol. 

Since Linux is case sensitive, it is unaffected by this issue as it treats the two as different files.

**Comment by csBlueChip** [comment]
Whoops.  Thanks for the feedback.  This should be fixed now.  
I've also renamed the other lowercase characters for consistency.
https://github.com/csBlueChip/FlipperZero_WiiEC/commit/bcaf987f06a5fcfa494dbe7186a9ee9e608a1bb9
